language: node_js
node_js:
  - "4.4"
  - "5.11"
  - "6.2"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - "npm i"
script: "npm test"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"